# Generated by Django 5.1.3 on 2024-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='custuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='custuser',
            name='username',
        ),
        migrations.AddField(
            model_name='custuser',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
